load("C:/Users/JiyingLi/Desktop/project221/.RData")
load(biomaRT)
load(biomaRT)
library(biomaRT)
library(limma)
library(edgeR)
library(biomaRt)
load("C:/Users/JiyingLi/Desktop/project221/geneCountEdgeR.RData")
install.packages(readr)
install.packages("readr")
source("https://bioconductor.org/biocLite.R")
biocLite("biomaRt")
setwd("C:/Users/JiyingLi/Desktop/project221limma")
getwd()
library(limma)
library("arrayQualityMetrics")
source("https://bioconductor.org/biocLite.R")
biocLite("arrayQualityMetrics")
biocLite("preprocessCore")
library("Biobase")
library("RColorBrewer")

install.packages( pkgs= "gplots" )
library("gplots")

x<-read.csv("space_fly_gene_counts.csv")
pca = prcomp(t(x))
head(x)
rownames(x)=x[,1]
head(x)
x<-subset(x, select=-X)
head(x)
class(x)
x
head(x)
x<-type.convert(x)
class(x)
pca = prcomp(t(x))
names = colnames(x)
fac= factor(c("G3","G1","G1","G1","G3","G3","G1","G3"))
colours = c("red","blue")


library("edgeR")
dge <- DGEList(counts=x)
head(dge)
class(dge)
head(dge$counts)
head(dge$samples)
dge <- calcNormFactors(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
fit <- lmFit(logCPM, design)
head(design)
colnames(design) <- c("G1 ", "G3")
design
fit <- lmFit(logCPM, design)
fit <- eBayes(fit, trend=TRUE)
topTable(fit, coef=ncol(design))
head(fit)
class(fit)
class(fit)
?topTable
topTableF(fit, number=20000)
topTableF(fit, number=20000)
dim(fit)
dim(fit$coefficients)
dim(fit$rank)
dim(fit$cov.coefficients)
write.csv(topTable(fit, number =13868), "limma_merge0.csv")
topTableF(fit, number=20)
v <- voom(dge, design, plot=TRUE)
v <- voom(counts, design, plot=TRUE)
v <- voom(counts, design, plot=TRUE, normalize="quantile")
View(x)
dge <- DGEList(counts=counts)
dge <- DGEList(counts=x)
dge <- calcNormFactors(dge)
head(dge)
head(dge$counts)
head(dge$samples)
dge$samples
View(design)
v <- voom(dge, design, plot=TRUE)
v <- voom(counts, design, plot=TRUE)
v <- voom(dge, design, plot=TRUE)
fit <- lmFit(v, design)
fit <- eBayes(fit)
topTable(fit, coef=ncol(design))
head(fit$coefficients)
head(fit$F.p.value)
head(fit$stdev.unscaled)
topTable(fit, coef=ncol(design))
?topTable
topTable(fit, coef=ncol(design), number=20)
topTable(fit, coef=ncol(design), number=10)
write.csv(topTable(fit, coef=ncol(design), number=15000))
write.csv(topTable(fit, coef=ncol(design), number=15000), "limma_merge0.csv")
merge1<-read.csv("limma_merge0.csv")
dim(merge1)
merge2<-subset(merge1, merge1$adj.P.Val<0.05)
dim(merge2)
merge3<-subset(merge2, merge2$logFC>1|merge2$logFC<(-1))
dim(merge3)
library(limma)
library(edgeR)
getwd()
View(x)
x<-x[!rowSums(x==0)>=1, ]
dim(x)
View(x)
pca = prcomp(t(x))
names = colnames(x)
fac= factor(c("G3","G1","G1","G1","G3","G3","G1","G3"))
colours = c("red","blue")

dge <- DGEList(counts=x)
dge <- calcNormFactors(dge)
v <- voom(dge, design, plot=TRUE)
fit <- lmFit(v, design)
fit <- eBayes(fit)
topTable(fit, coef=ncol(design))
write.csv(topTable(fit, coef=ncol(design), number=15000), "M0.CSV")
fit <- treat(fit, lfc=log2(1.2))
topTreat(fit, coef=ncol(design))
write.csv(topTable(fit, coef=ncol(design), number=15000), "N0.CSV")
write.csv(topTreat(fit, coef=ncol(design), number=15000), "M0.CSV")
write.csv(topTreat(fit, coef=ncol(design), number=15000), "M0.CSV")
fit <- treat(fit, lfc=log4(1.2))
fit <- treat(fit, lfc=log2(2))
topTreat(fit, coef=ncol(design))
fit <- treat(fit, lfc=log2(10))
topTreat(fit, coef=ncol(design))
fit <- treat(fit, lfc=log2(100))
topTreat(fit, coef=ncol(design))
?topTreat
topTable(fit, coef=ncol(design))
write.csv(topTreat(fit, coef=ncol(design)), "N1.csv")
install.packages( pkgs= "gplots" )
library("gplots")

dim(dge)
logCPM <- cpm(dge, log=TRUE, prior.count=3)
trend_fit <- lmFit(logCPM, design)
trend_fit <- eBayes(trend_fit, trend=TRUE)
topTable(topTable(fit, coef=ncol(design)), coef=ncol(design))
topTable(trend_fit, coef=ncol(design))
?cmp
?prior.count
logCPM <- cpm(dge, log=TRUE, prior.count=10)
trend_fit <- lmFit(logCPM, design)
trend_fit <- eBayes(trend_fit, trend=TRUE)
topTable(trend_fit, coef=ncol(design))

logCPM <- cpm(dge, log=TRUE, prior.count=100)
trend_fit <- lmFit(logCPM, design)
trend_fit <- eBayes(trend_fit, trend=TRUE)
topTable(trend_fit, coef=ncol(design))
v <- voom(dge, design, plot=TRUE)
v <- voom(counts, design, plot=TRUE)
v <- voom(x, design, plot=TRUE)
fit <- lmFit(v, design)
fit <- eBayes(fit)
topTable(fit, coef=ncol(design))
?topTable
write.csv(topTable(fit, coef=ncol(design) , number=15000), "limma_sig_gene.csv")
merge1<-read.csv("limma_sig_gene.csv")
dim(merge1)
merge2<-subset(merge1, merge1$P.Value<0.05)
dim(merge2)
merge2<-subset(merge1, merge1$logFC>1|merge1$logFC<(-1))
merge3<-subset(merge2, merge2$logFC>8.5|merge2$logFC<(-2.5))
dim(merge3)
write.csv(merge2, "limma_sig_genes.csv")
write.csv(merge3, "limma_sig_genes_8.5_2.5.csv")
savehistory("C:/Users/JiyingLi/Desktop/project221limma/limma.r")
